[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[build]
command = "npm run build"
publish ="/build"
base ="/"

[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/index.html"
